---
- name: configure banner
  hosts: all
 
  collections:
   - arubanetworks.aoscx

  tasks:
  - name: Create VLAN 200 with description
    aoscx_vlan:
      vlan_id: 200
      description: This is VLAN 200

  - name: Create VLAN Interface 200
    aoscx_vlan_interface:
      vlan_id: 200
      description: UPLINK_VLAN
      ipv4: ['10.20.20.1/24']
      ipv6: ['3000:db8::1234/64']
      vrf: red
      ip_helper_address: ['10.40.20.1']
